import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gabriel Trigo\'s Personal Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-zinc-100">
      <body className="pt-12 bg-slate-50">{children}</body>
    </html>
  )
}
